USE [master]
GO
/****** Object:  Database [Hmo]    Script Date: 28/03/2024 18:06:40 ******/
CREATE DATABASE [Hmo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hmo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Hmo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Hmo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Hmo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Hmo] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hmo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Hmo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Hmo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Hmo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Hmo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Hmo] SET ARITHABORT OFF 
GO
ALTER DATABASE [Hmo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Hmo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Hmo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Hmo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Hmo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Hmo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Hmo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Hmo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Hmo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Hmo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Hmo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Hmo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Hmo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Hmo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Hmo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Hmo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Hmo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Hmo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Hmo] SET  MULTI_USER 
GO
ALTER DATABASE [Hmo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Hmo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Hmo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Hmo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Hmo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Hmo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Hmo] SET QUERY_STORE = OFF
GO
USE [Hmo]
GO
/****** Object:  Table [dbo].[address]    Script Date: 28/03/2024 18:06:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[address](
	[addressCode] [int] IDENTITY(1,1) NOT NULL,
	[cityCode] [int] NULL,
	[street] [varchar](50) NULL,
	[houseNumber] [int] NULL,
 CONSTRAINT [PK_adrress] PRIMARY KEY CLUSTERED 
(
	[addressCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[city]    Script Date: 28/03/2024 18:06:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[city](
	[cityCode] [int] IDENTITY(1,1) NOT NULL,
	[cityName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_city] PRIMARY KEY CLUSTERED 
(
	[cityCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[coronaPatient]    Script Date: 28/03/2024 18:06:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[coronaPatient](
	[coronaPatientId] [varchar](9) NOT NULL,
	[PositivityDate] [date] NULL,
	[recoveryDate] [date] NULL,
 CONSTRAINT [PK_coronaPatient] PRIMARY KEY CLUSTERED 
(
	[coronaPatientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[patient]    Script Date: 28/03/2024 18:06:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[patient](
	[id] [varchar](9) NOT NULL,
	[firstName] [varchar](30) NOT NULL,
	[lastName] [varchar](50) NOT NULL,
	[addressCode] [int] NOT NULL,
	[dateOfBirth] [date] NOT NULL,
	[phone] [varchar](10) NULL,
	[mobilePhone] [varchar](50) NULL,
 CONSTRAINT [PK_client] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[vaccine]    Script Date: 28/03/2024 18:06:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[vaccine](
	[vaccineCode] [int] IDENTITY(1,1) NOT NULL,
	[patientId] [varchar](9) NOT NULL,
	[dateOfVaccine] [date] NOT NULL,
	[vaccineManufacturerCode] [int] NOT NULL,
 CONSTRAINT [PK_vaccine] PRIMARY KEY CLUSTERED 
(
	[vaccineCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[vaccineManufacturer]    Script Date: 28/03/2024 18:06:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[vaccineManufacturer](
	[vaccineManufacturerCode] [int] IDENTITY(1,1) NOT NULL,
	[manufacturerName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_vaccineManufacturer] PRIMARY KEY CLUSTERED 
(
	[vaccineManufacturerCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[address]  WITH CHECK ADD  CONSTRAINT [FK_adrress_city] FOREIGN KEY([cityCode])
REFERENCES [dbo].[city] ([cityCode])
GO
ALTER TABLE [dbo].[address] CHECK CONSTRAINT [FK_adrress_city]
GO
ALTER TABLE [dbo].[coronaPatient]  WITH CHECK ADD  CONSTRAINT [FK_coronaPatient_patient] FOREIGN KEY([coronaPatientId])
REFERENCES [dbo].[patient] ([id])
GO
ALTER TABLE [dbo].[coronaPatient] CHECK CONSTRAINT [FK_coronaPatient_patient]
GO
ALTER TABLE [dbo].[patient]  WITH CHECK ADD  CONSTRAINT [FK_patient_adrress] FOREIGN KEY([addressCode])
REFERENCES [dbo].[address] ([addressCode])
GO
ALTER TABLE [dbo].[patient] CHECK CONSTRAINT [FK_patient_adrress]
GO
ALTER TABLE [dbo].[vaccine]  WITH CHECK ADD  CONSTRAINT [FK_vaccine_patient] FOREIGN KEY([patientId])
REFERENCES [dbo].[patient] ([id])
GO
ALTER TABLE [dbo].[vaccine] CHECK CONSTRAINT [FK_vaccine_patient]
GO
ALTER TABLE [dbo].[vaccine]  WITH CHECK ADD  CONSTRAINT [FK_vaccine_vaccineManufacturer] FOREIGN KEY([vaccineManufacturerCode])
REFERENCES [dbo].[vaccineManufacturer] ([vaccineManufacturerCode])
GO
ALTER TABLE [dbo].[vaccine] CHECK CONSTRAINT [FK_vaccine_vaccineManufacturer]
GO
USE [master]
GO
ALTER DATABASE [Hmo] SET  READ_WRITE 
GO
